# Generated by Django 4.1.2 on 2022-10-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceHistory',
        ),
    ]
