# Generated by Django 4.1.2 on 2022-10-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='previousBalance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
