# Generated by Django 4.1.2 on 2022-10-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_operation_previousbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='currenteBalance',
            new_name='currentBalance',
        ),
    ]
